version: '3.8'
services:
  mongo-container:
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - mongodb_data_container2:/data/db

volumes:
  mongodb_data_container2:
    driver: local
