version: '3.8'
services:
  app:
    build:
      context: ./src
      target: debug
    container_name: app-container
    ports:
      - "80:8080"
    volumes:
      - ./src:/usr/src/app/
      - /usr/src/app/node_modules
      - /usr/src/app/assets/videos
      - /usr/src/app/public/admin/img/thumbnails
      - /usr/src/app/public/site/img/temp
    # volumes:
    #   - app-assets:/usr/src/app/assets
    #   - app-admin-img:/usr/src/app/public/admin/img
    #   - app-site-img:/usr/src/app/public/site/img
    env_file: .env.development
    environment:
      - TZ=America/Panama
      - NODE_ENV=development

volumes:
  app-assets:
    driver: local
  app-admin-img:
    driver: local
  app-site-img:
    driver: local
