version: '3.8'
services:
  redis:
    image: "redis:7.2-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - /data
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: youtube
    command: mongod --auth

  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    volumes:
    - ./src:/usr/src/app/
    - /usr/src/app/node_modules
    - app-assets:/usr/src/app/assets
    - app-admin-img:/usr/src/app/public/admin/img/thumbnails
    - app-site-img:/usr/src/app/public/site/img/temp
    # volumes:
    # - app-assets:/usr/src/app/assets
    # - app-admin-img:/usr/src/app/public/admin/img/thumbnails
    # - app-site-img:/usr/src/app/public/site/img/temp
    depends_on:
      - mongo
    networks:
      - app-network
    env_file: .env.development
    environment:
      - TZ=Europe/London
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_container:
    driver: local
  app-assets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw,nfsvers=4
      device: :/exports/assets
  app-admin-img:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw,nfsvers=4
      device: :/exports/public/admin/img/thumbnails
  app-site-img:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_SERVER_IP>,rw,nfsvers=4
      device: :/exports/public/site/img/temp
