version: '3.8'
services:
  app:
    build:
      context: ./src
      target: debug
    container_name: app-container
    ports:
      - "8080:8080"
    volumes:
    - ./src:/usr/src/app/
    - /usr/src/app/node_modules
    - nfs-assets:/usr/src/app/assets
    - nfs-admin-img:/usr/src/app/public/admin/img/thumbnails
    - nfs-site-img:/usr/src/app/public/site/img/temp
    env_file: .env.development
    environment:
      - TZ=America/Panama
      - NODE_ENV=development

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    privileged: true
    environment:
      - SHARED_DIRECTORY=/exports
    ports:
      - "2049:2049"
    volumes:
      - ./exports:/exports

volumes:
  nfs-assets:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,rw,nfsvers=4
      device: :/exports/assets
  nfs-admin-img:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,rw,nfsvers=4
      device: :/exports/public/admin/img/thumbnails
  nfs-site-img:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,rw,nfsvers=4
      device: :/exports/public/site/img/temp
