version: '3.8'
services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    platform: linux/amd64
    privileged: true
    environment:
      - SHARED_DIRECTORY=/exports
    ports:
      - "2049:2049"
    volumes:
      # - /Users/alexander/Code/Development/Larissa_docs/Development/VideoApp/exports:/exports
      - /tmp/exports:/exports