version: '3.8'
services:
  app:
    build:
      context: ./src
      target: debug
    container_name: app-container
    ports:
      - "8080:8080"
    volumes:
    - ./src:/usr/src/app/
    - /usr/src/app/node_modules
    - app-assets:/usr/src/app/assets
    - app-admin-img:/usr/src/app/public/admin/img/thumbnails
    - app-site-img:/usr/src/app/public/site/img/temp
    # volumes:
    # - app-assets:/usr/src/app/assets
    # - app-admin-img:/usr/src/app/public/admin/img/thumbnails
    # - app-site-img:/usr/src/app/public/site/img/temp
    env_file: .env.development
    environment:
      - TZ=America/Panama
      - NODE_ENV=development

volumes:
  app-assets:
    driver: local
  app-admin-img:
    driver: local
  app-site-img:
    driver: local
