version: '3.8'
services:
  redis:
    image: "redis:7.2-alpine"
    container_name: redis
    ports:
      - "127.0.0.1:6380:6379"
    restart: unless-stopped
    volumes:
      - /data
  app:
    image: kuzurik797/videoapp-stripe:latest
    pull_policy: always
    platform: linux/amd64 
    container_name: app-container
    ports:
      - "127.0.0.1:80:8080"
    volumes:
      - ./exports/assets:/usr/src/app/assets
      - ./exports/public/admin:/usr/src/app/public/admin
      - ./exports/public/site:/usr/src/app/public/site
    env_file: .env.development
    environment:
      - TZ=America/Panama
      - NODE_ENV=development # Yet for some features that might not work with HTTP (ex. my current setup with Express Session cookies)
