version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container27:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: youtube
    command: mongod --auth

  app:
    build: .
    container_name: app-container
    ports:
      - "4300:4300"
    volumes:
      # - .:/usr/src/app/
      # - /usr/src/app/node_modules
      - app-assets8:/usr/src/app/assets
      - app-admin-img8:/usr/src/app/public/admin/img
      - app-site-img8:/usr/src/app/public/site/img
    depends_on:
      - mongo
    networks:
      - app-network
    env_file: development.env
    environment:
      - TZ=Europe/London
      - NODE_ENV=development

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_container27:
    driver: local
  app-assets8:
    driver: local
  app-admin-img8:
    driver: local
  app-site-img8:
    driver: local
