version: '3.8'
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-db
    volumes:
      - $PWD/redis-data:/var/lib/redis-stack
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command: redis-stack-server /usr/local/etc/redis/redis.conf
