---
# Standalone Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
# App Service
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: video-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
#