apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: video-app
data:
  STRIPE_PUBLISHABLE_KEY: *
  STRIPE_SECRET_KEY: *
  JWT_SEC: *
  PORT: *
  MONGO_HOST: *
  MONGO_PORT: *
  MONGO_USER: *
  MONGO_PASSWORD: *
  MONGO_DATABASE: *
  SESSION_SECRET: *
  CURRENCY: *
  DOMAIN_EMAIL: *
  ADMIN_EMAIL: *
  EMAIL_APP_PASSWORD: *
  EXPRESS_SESSION_SECRET: *
  EXPRESS_SESSION_KEY: *
  DOMAIN: *
  REDIS_HOST: *
  REDIS_PORT: *
  # REDIS_HOST: *
  # REDIS_HOST: *
  # REDIS_PASSWORD: *
