apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: default
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ${DOMAIN_NAME}
  dnsNames:
    - ${DOMAIN_NAME}
