apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-admin-img-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-admin-img-pv
