apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-site-img-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-site-img-pv
#