apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
            - name: nfs-server
              image: itsthenetwork/nfs-server-alpine:latest
              ports:
                - containerPort: 2049
              securityContext:
                privileged: true
              env:
                - name: SHARED_DIRECTORY
                  value: /exports
              volumeMounts:
                - name: nfs-exports
                  mountPath: /exports
      volumes:
        - name: nfs-exports
          hostPath:
            # path: /Users/alexander/Code/Development/Larissa_docs/Development/VideoApp/exports
            path: /home/vagrant/Code/Video-streaming-app/exports
            type: Directory
