apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-admin-img-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /Users/alexander/Code/Development/Larissa_docs/Development/VideoApp/src/public/admin
    server: 10.170.174.117
