apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-assets-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
  path: /home/vagrant/Code/Video-streaming-app/src/assets
  server: 192.168.236.172
