apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-assets-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/assets
    server: nfs-server.default.svc.cluster.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-assets-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-assets-pv
