apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-assets-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /Users/alexander/Code/Development/Larissa_docs/Development/VideoApp/src/assets
    server: 10.170.174.117
