apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-admin-img-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
  path: /home/vagrant/Code/Video-streaming-app/src/public/admin
  server: 192.168.236.172
