auth:
  enabled: true
  existingSecret: redis-password

architecture: standalone

master:
  persistence:
    enabled: true
    size: 1Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: 1Gi

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

service:
  type: ClusterIP
