#cloud-config
users:
  - name: main
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    sudo: ["ALL=(ALL) ALL"]
    ssh-authorized-keys:
      - ${ssh_public_key}
    plain_text_passwd: ${main_user_password}
package_update: true
package_upgrade: true
