---
- hosts: droplets
  become: yes
  tasks:
    - name: Install NFS server packages
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create export directory
      file:
        path: /srv/nfs_share
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configure NFS exports
      copy:
        dest: /etc/exports
        content: |
          /srv/nfs_share  *(rw,sync,no_subtree_check,no_root_squash)
      notify: Restart NFS

  handlers:
    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted
